version: "3.3"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=kuepa
      - POSTGRES_PASSWORD=kuepa
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
